### ISSUE TITLE
Static code analysis - future idea

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/docs-and-discussions#10]
**Opening this issue as a reminder more than an actual issue.**

Implementation of static code analysis using official GitHub CodeQL actions is in progress. _Note: it has the same core as what LGTM but hosted in an action instead of being a 3rd party app._

The current analyze job looks like this:
```yml
analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - 'javascript'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
```

I first tried to create a new action to wrap all those steps so that we could just do something like:
```yml
analyze:
  name: Analyze
  runs-on: ubuntu-latest
  strategy:
      fail-fast: false
      matrix:
        language:
          - 'javascript'
  steps:
  - name: Checkout repository
    uses: actions/checkout@v2
  - name: Run static code analysis
    uses: kaskadi/action-codeql-analysis@master
    with:
      languages: ${{ matrix.language }}
```

This ideally would have allow us to simplify the workflow syntax (not need to repeat the 3 same steps over multiple workflows and multiple repositories) and pass any configuration we need for the analysis down to our action.

Unfortunately we currently cannot run actions in action (see [here](https://github.com/actions/runner/issues/438) and [there](https://github.com/actions/runner/issues/646)).

This seemed to be planned, but it does not seem to have a high priority for the GitHub team so I leave this open until the support for fully composite actions drops and I can apply the logic described above.
